### ISSUE TITLE
Hello! How can I change the background color of the terminal scrollbar? 

### ISSUE THREAD

**Issue by zhouxinghong** [catppuccin/windows-terminal#10]
Hello! How can I change the background color of the terminal scrollbar?
1.16
Windows 10

**Comment by nekowinston** [comment]
Hi there! I don't use Windows, but I can ask the most recent contributor.

@aryanprince any input on this issue? Does #8 fix this?

**Comment by aryanprince** [comment]
@zhouxinghong Had a look at docs and release notes, couldn't find any info for customizing the scroll bar color.

Worth asking a question over at [github.com/microsoft/terminal](https://github.com/microsoft/terminal).

**Comment by nekowinston** [comment]
Yeah a quick search seems to indicate that the only "styling" option there is regarding the scrollbar, is toggling its visibility: https://github.com/microsoft/terminal/blob/fb597ed304ec6eef245405c9652e9b8a029b821f/doc/specs/Proto%20extensions-spec.md#example-of-a-full-json-file

Will close this for now, we can create a new one/reopen this should a theming option get added in future.

**Comment by zhouxinghong** [comment]
Yes it is possible to create a question allowing the user to customize the scrollbar style.
