### ISSUE TITLE
Folders looks not good

### ISSUE THREAD

**Issue by 88srzh** [catppuccin/windows-terminal#11]
![Screenshot_119](https://user-images.githubusercontent.com/61797666/213414222-95fb4970-c191-437c-a98c-8af8a5d769e2.jpg)

files look good, unlike folders

**Comment by nekowinston** [comment]
That seems like an issue with the shell, not the Terminal theme. On Linux, you would fix this by changing LS_COLORS, e.g. using [vivid](https://github.com/sharkdp/vivid).

**Comment by LudoPinelli** [comment]
Yes, colors of commands, errors, folders etc, require to configure the shell, not the terminal. For Powershell, you can check https://github.com/Davlind/PSColor which will allow you to define exactly how you want them to appear.

**Comment by 88srzh** [comment]
thx that's work for me. Now I just need catppuccin colors for PSColors :)

**Comment by cbmek** [comment]
@88srzh, you don't need any modules, just put this in your $PROFILE:

```
if ($PSStyle)
{
    $PSStyle.FileInfo.Directory = "`e[96m"
    $PSStyle.FileInfo.Executable = "`e[95m"
    $PSStyle.FileInfo.SymbolicLink  = "" 
    $PSStyle.FileInfo.Extension.Clear()
}
```

...and if you want to use different colors, then just call `$PSStyle` and copy paste magic numbers you prefer to your $PROFILE

![image](https://github.com/catppuccin/windows-terminal/assets/1478006/647728a4-767f-483b-9455-6a4ef8962187)

**Comment by nithin-mk** [comment]
Is it possible to use https://github.com/catppuccin/powershell/ for this purpose? I did not quite understand the instructions given there.
