### ISSUE TITLE
Change selection highlight to surface2

### ISSUE THREAD

**Issue by nekowinston** [catppuccin/windows-terminal#5]
A PR was just opened to include this in https://github.com/atomcorp/themes/pull/86.

The selection highlight in that PR differs from our repository, it uses `rosewater` as the cursor colour, and `surface2` as the selection colour,

Would be nice if we could change this so "upstream" is the same.

Thanks to @caarlos0 for implementing a fixed version of the theme!

**Comment by caarlos0** [comment]
@nekowinston it was actually copied from https://gist.github.com/jolheiser/2721bac5a1452cc5724b924346bdc5aa

credit is due to @jolheiser 🤘

**Comment by caarlos0** [comment]
btw, n https://github.com/atomcorp/themes/pull/86 is now merged!
