### ISSUE TITLE
Hello! The background color of the Terminal tab cannot be changed, how did you do it?

### ISSUE THREAD

**Issue by zhouxinghong** [catppuccin/windows-terminal#9]
Hello! After I follow your instructions in Terminal_Win10_1.15.3465, the background color of the Terminal tab cannot be changed. How did you do it?
![2023-01-14_180604](https://user-images.githubusercontent.com/54253524/212466751-2f076d1d-d3b1-463a-892a-ba0b05d9dacd.png)

**Comment by nyxkrage** [comment]
As specified in the README
> (Only in Windows Terminal 1.16 Preview) Copy the contents of flavourTheme.json into the opened json file under "themes": ...

You need version 1.16 Preview to theme that part of the terminal

**Comment by zhouxinghong** [comment]
Thanks a lot for your answer! But where can flavorTheme.json be found?

**Comment by aryanprince** [comment]
@zhouxinghong Should be in root directory of this repo. Link to one here: https://github.com/catppuccin/windows-terminal/blob/main/frappeTheme.json

**Comment by zhouxinghong** [comment]
> @zhouxinghong Should be in root directory of this repo. Link to one here: https://github.com/catppuccin/windows-terminal/blob/main/frappeTheme.json

Thank you very much for your answer!👍😜
